filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /opt/logs/*.log
    fields:
      IP: "服务器IP"
    fields_under_root: true
    multiline:
      pattern: '^\d{4}-\d{2}-\d{2}'
      negate: true
      match: after
  
setup.template.name: "Log"
setup.template.pattern: "Log"
setup.template.overwrite: true
setup.template.enabled: true
setup.ilm.enabled: false

output.elasticsearch:
  hosts: ["es服务器IP:9200"]
  index: "Log"
  pipeline: "log-pipeline"