filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /opt/logs/*.log
    fields:
      IP: "服务器IP"
    fields_under_root: true
    multiline:
      pattern: '^\d{4}-\d{2}-\d{2}'
      negate: true
      match: after
      tags: ["log"]

output.elasticsearch:
  hosts: ["es服务器IP:9200"]
  pipeline: "log-pipeline"
  indices:
    - index: "log-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.contains:
        tags: "log"
