version: "3.8"

services:

  filebeat:
    image: elastic/filebeat:7.8.0
    container_name: filebeat
    restart: always
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /opt/logs/:/opt/logs/
